name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances du backend
        working-directory: ./backend
        run: npm install

      - name: Lancer les tests backend
        working-directory: ./backend
        run: npm test

      - name: Build image Docker backend
        run: docker build -t tp_final-backend ./backend

      - name: Build image Docker frontend
        run: docker build -t tp_final-frontend ./frontend